[package]
name = "jace"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.org>"]
repository = "https://github.org/nekodjin/jace"
description = "Reserved for the Jace ISA reference assembler and emulator."

[dependencies]
